# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'line_detection.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1019, 839)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame.setStyleSheet("QFrame{\n"
"    background-color:rgb(81,81,81);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 2)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_8 = QtWidgets.QFrame(self.frame)
        self.frame_8.setStyleSheet("QFrame{\n"
"    background-color:rgb(60,63,65);\n"
"}")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_3.setContentsMargins(2, 2, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.pushButton_10 = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_10.setMinimumSize(QtCore.QSize(50, 0))
        self.pushButton_10.setStyleSheet("QPushButton{\n"
"    background-color: transparent;\n"
"    color: white;\n"
"    font-size: 20pt;\n"
"    border:none;\n"
"}\n"
"QPushButton:hover {  \n"
"    background-color:rgb(79,82,84);\n"
"}")
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_3.addWidget(self.pushButton_10)
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_9.setMinimumSize(QtCore.QSize(50, 0))
        self.pushButton_9.setStyleSheet("QPushButton{\n"
"    background-color: transparent;\n"
"    color: white;\n"
"    font-size: 15pt;\n"
"    border:none;\n"
"}\n"
"QPushButton:hover {  \n"
"    background-color:rgb(79,82,84);\n"
"}")
        self.pushButton_9.setText("")
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_3.addWidget(self.pushButton_9)
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_8.setMinimumSize(QtCore.QSize(50, 0))
        self.pushButton_8.setStyleSheet("QPushButton{\n"
"    background-color: transparent;\n"
"    color: white;\n"
"    font-size: 20pt;\n"
"    border:none;\n"
"}\n"
"QPushButton:hover {  \n"
"    background-color:rgb(232,17,35);\n"
"\n"
"}")
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_3.addWidget(self.pushButton_8)
        self.verticalLayout_3.addWidget(self.frame_8)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 553))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 10000))
        self.frame_2.setStyleSheet("QFrame{\n"
"    background-color:rgb(60,63,65);\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(9, -1, -1, -1)
        self.horizontalLayout.setSpacing(1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_10 = QtWidgets.QFrame(self.frame_2)
        self.frame_10.setStyleSheet("QFrame{\n"
"    background-color:rgb(43,43,43);\n"
"}")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label = QtWidgets.QLabel(self.frame_10)
        self.label.setStyleSheet("QLabel { \n"
"    color:rgb(255, 255, 255);\n"
"    font-size: 100px;\n"
"    text-align: center;\n"
"    font-family: \"黑体\";\n"
"}")
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.horizontalLayout.addWidget(self.frame_10)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 200))
        self.frame_3.setStyleSheet("QFrame{\n"
"    background-color:rgb(59,71,84);\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 500))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_4.setSpacing(2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_9 = QtWidgets.QFrame(self.frame_5)
        self.frame_9.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_9.setStyleSheet("QFrame{\n"
"    background-color:rgb(60,63,65);\n"
"}")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_9)
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"    background-color:rgba(0, 0, 0,0);\n"
"    border:none;\n"
"    height:40px;\n"
"    color:rgb(255, 255, 255);\n"
"    font-size: 25px;\n"
"    font-family: \"黑体\";\n"
"}\n"
"\n"
"QPushButton:hover {  \n"
"    background-color:rgb(0, 174, 236);\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_6.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_9)
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"    background-color:rgba(0, 0, 0,0);\n"
"    border:none;\n"
"    height:40px;\n"
"    color:rgb(255, 255, 255);\n"
"    font-size: 25px;\n"
"    font-family: \"黑体\";\n"
"}\n"
"\n"
"QPushButton:hover {  \n"
"    background-color:rgb(0, 174, 236);\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_6.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_9)
        self.pushButton_5.setStyleSheet("QPushButton{\n"
"    background-color:rgba(0, 0, 0,0);\n"
"    border:none;\n"
"    height:40px;\n"
"    color:rgb(255, 255, 255);\n"
"    font-size: 25px;\n"
"    font-family: \"黑体\";\n"
"}\n"
"\n"
"QPushButton:hover {  \n"
"    background-color:rgb(0, 174, 236);\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_6.addWidget(self.pushButton_5)
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_9)
        self.pushButton_6.setStyleSheet("QPushButton{\n"
"    background-color:rgba(0, 0, 0,0);\n"
"    border:none;\n"
"    height:40px;\n"
"    color:rgb(255, 255, 255);\n"
"    font-size: 25px;\n"
"    font-family: \"黑体\";\n"
"}\n"
"\n"
"QPushButton:hover {  \n"
"    background-color:rgb(0, 174, 236);\n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_6.addWidget(self.pushButton_6)
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_9)
        self.pushButton_7.setStyleSheet("QPushButton{\n"
"    background-color:rgba(0, 0, 0,0);\n"
"    border:none;\n"
"    height:40px;\n"
"    color:rgb(255, 255, 255);\n"
"    font-size: 25px;\n"
"    font-family: \"黑体\";\n"
"}\n"
"\n"
"QPushButton:hover {  \n"
"    background-color:rgb(0, 174, 236);\n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_6.addWidget(self.pushButton_7)
        self.pushButton_11 = QtWidgets.QPushButton(self.frame_9)
        self.pushButton_11.setStyleSheet("QPushButton{\n"
"    background-color:rgba(0, 0, 0,0);\n"
"    border:none;\n"
"    height:40px;\n"
"    color:rgb(255, 255, 255);\n"
"    font-size: 25px;\n"
"    font-family: \"黑体\";\n"
"}\n"
"\n"
"QPushButton:hover {  \n"
"    background-color:rgb(0, 174, 236);\n"
"}")
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_6.addWidget(self.pushButton_11)
        self.pushButton_12 = QtWidgets.QPushButton(self.frame_9)
        self.pushButton_12.setStyleSheet("QPushButton{\n"
"    background-color:rgba(0, 0, 0,0);\n"
"    border:none;\n"
"    height:40px;\n"
"    color:rgb(255, 255, 255);\n"
"    font-size: 25px;\n"
"    font-family: \"黑体\";\n"
"}\n"
"\n"
"QPushButton:hover {  \n"
"    background-color:rgb(0, 174, 236);\n"
"}")
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_6.addWidget(self.pushButton_12)
        self.verticalLayout_4.addWidget(self.frame_9)
        self.frame_11 = QtWidgets.QFrame(self.frame_5)
        self.frame_11.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_11.setStyleSheet("QFrame{\n"
"    background-color:rgb(60,63,65);\n"
"}")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButton = QtWidgets.QPushButton(self.frame_11)
        self.pushButton.setStyleSheet("QPushButton{\n"
"    background-color:rgba(0, 0, 0,0);\n"
"    border:none;\n"
"    height:40px;\n"
"    color:rgb(255, 255, 255);\n"
"    font-size: 25px;\n"
"    font-family: \"黑体\";\n"
"}\n"
"\n"
"QPushButton:hover {  \n"
"    background-color:rgb(0, 174, 236);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_7.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_11)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    background-color:rgba(0, 0, 0,0);\n"
"    border:none;\n"
"    height:40px;\n"
"    color:rgb(255, 255, 255);\n"
"    font-size: 25px;\n"
"    font-family: \"黑体\";\n"
"}\n"
"\n"
"QPushButton:hover {  \n"
"    background-color:rgb(0, 174, 236);\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_7.addWidget(self.pushButton_2)
        self.verticalLayout_4.addWidget(self.frame_11)
        self.verticalLayout_2.addWidget(self.frame_5)
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_7 = QtWidgets.QFrame(self.frame_4)
        self.frame_7.setMinimumSize(QtCore.QSize(10, 0))
        self.frame_7.setMaximumSize(QtCore.QSize(15, 16777215))
        self.frame_7.setStyleSheet("QFrame{\n"
"    background-color:rgb(60,63,65);\n"
"}")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_2.addWidget(self.frame_7)
        self.frame_6 = QtWidgets.QFrame(self.frame_4)
        self.frame_6.setStyleSheet("QFrame{\n"
"    background-color:rgb(43,43,43);\n"
"}")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, -1)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.textBrowser = QtWidgets.QTextBrowser(self.frame_6)
        self.textBrowser.setStyleSheet("QTextBrowser { \n"
"    font-family: \'Arial\'; \n"
"    font-size: 12pt; \n"
"    color: white; \n"
"    scrollbar-face-color: rgb(86,86,86);\n"
"    scrollbar-shadow-color: transparent;\n"
"    font-family: \"黑体\";\n"
"}")
        self.textBrowser.setObjectName("textBrowser")
        self.horizontalLayout_4.addWidget(self.textBrowser)
        self.horizontalLayout_2.addWidget(self.frame_6)
        self.verticalLayout_2.addWidget(self.frame_4)
        self.verticalLayout.addWidget(self.frame_3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_10.setText(_translate("MainWindow", "-"))
        self.pushButton_8.setText(_translate("MainWindow", "×"))
        self.label.setText(_translate("MainWindow", "   车道线检测系统"))
        self.pushButton_3.setText(_translate("MainWindow", "灰度化"))
        self.pushButton_4.setText(_translate("MainWindow", "模糊滤波"))
        self.pushButton_5.setText(_translate("MainWindow", "二值化"))
        self.pushButton_6.setText(_translate("MainWindow", "边缘检测"))
        self.pushButton_7.setText(_translate("MainWindow", "车道线检测"))
        self.pushButton_11.setText(_translate("MainWindow", "障碍检测"))
        self.pushButton_12.setText(_translate("MainWindow", "视频检测"))
        self.pushButton.setText(_translate("MainWindow", "打开文件"))
        self.pushButton_2.setText(_translate("MainWindow", "文件保存"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'黑体\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial\';\">欢迎使用本车道线检测系统</span></p></body></html>"))
